### ISSUE TITLE
ore detection for extreme reactors mod wrong

### ISSUE THREAD

**Issue by Linrox** [NicosaurusRex99/Generous-Ores#2]
The extreme reactors mod uses yellorium as the dust (from macerating) and yellorite as the world gen ore. 
But when i look at the config file there is no mention of the ore as an option to config (min/max/tries/vein)
But after a /oredistribution scan to shows in the results as yellorium, which is wrong as it should be yellorite ore.

Minecraft version:1.12.2
Forge Verison:14.23.4.2705
Generous ores version:1.12.2.1
Extreme Reactors Version:1.12.2-0.4.5.49

**Comment by NicosaurusRex99** [comment]
What mod has /oredistribution? also great report thank you

**Comment by NicosaurusRex99** [comment]
I will get around to adding it now :D

**Comment by NicosaurusRex99** [comment]
Added in 1002361

**Comment by Linrox** [comment]
One further query, What happens if you separate yellorite and uranium in the extreme reactors mod config. as there is an option to do so. Will generous ores still show yellorite or only focus on uranium.
